---
title: "Income Data from IRS"
author: "Fatemeh Kazemi"
date: "01-02-2021"
output:
  html_document:
    df_print: paged
---

### This program:
  (1) Reads and cleans behavioral data by BRFSS

```{r load packages}
library(tidyverse)
library(here)
library(sas7bdat)
library(zoo) #na.fill
```
```{r}
load('C:\\Users\\fkazem01\\Box\\Projects\\PM Components\\data\\processed\\aqs-sites.RDa')
load(here('data', 'processed','county-zip.RDa'))
```

```{r }
dt.brfss.raw <- read.sas7bdat(here('data','raw','brfss0212.sas7bdat')) %>% 
    transmute(St.County = fips,
              Year = year,
              Month = month,
              X_bmi_Mean,
              X_raceg_Prop,
              X_rfsmok_Prop,
              X_diabetes_Prop,
              X_asthma_Prop,
              X_rfdrhv_Prop) %>%
  arrange(St.County, Year, Month) %>% 
  group_by(St.County) %>% 
  mutate_at(.vars = c("X_bmi_Mean","X_raceg_Prop","X_rfsmok_Prop",
                      "X_diabetes_Prop","X_asthma_Prop","X_rfdrhv_Prop"),
            ~na.fill(.x, "extend"))

save(dt.brfss.raw, file = here('data', 'raw', 'brfss-raw.RDa'))

dt.brfss.raw %>% 
  group_by(Year) %>% 
  summarise(n_county = length(unique(St.County)))
# min : 2002 > 146
# max : 2010 > 302

dt.brfss.raw %>% 
  filter(Year < 2009) %>% 
  distinct(St.County) %>% 
  nrow() #438 # <2009:378
```

```{r}
dt.brfss.site <- dt.aqs.sites %>% 
  transmute(Site.ID,
            St.County = as.factor(paste(State.Code, County.Code, sep =""))) %>% 
  inner_join(dt.brfss.raw) %>% 
  select(-St.County)

save(dt.brfss.site, file = here('data', 'processed', 'brfss-site.RDa'))
write.csv(dt.brfss.site, file = here('data', 'processed', 'brfss-site.csv'),
          row.names = F)

dt.brfss.site %>% distinct(Site.ID) %>% nrow() #3468 
#388counties
```

```{r}
dt.brfss.zip <- dt.county.zip %>% 
  inner_join(dt.brfss.raw) %>% 
  group_by(Zip.Code, Year, Month) %>% 
  summarise(X_bmi_Mean = mean(X_bmi_Mean),
            X_raceg_Prop = mean(X_raceg_Prop),
            X_rfsmok_Prop = mean(X_rfsmok_Prop),
            X_diabetes_Prop = mean(X_diabetes_Prop),
            X_asthma_Prop = mean(X_asthma_Prop),
            X_rfdrhv_Prop = mean(X_rfdrhv_Prop)) %>% 
  as.data.frame()
              
save(dt.brfss.zip, file = here('data', 'processed', 'brfss-zip.RDa'))
write.csv(dt.brfss.zip, file = here('data', 'processed', 'brfss-zip.csv'),
          row.names = F)

dt.brfss.zip %>% distinct(Zip.Code) %>% nrow() #16218

dt.county.zip %>% 
  inner_join(dt.brfss.raw) %>% 
  filter(Year < 2009) %>% 
  distinct(St.County) %>% 
  nrow() #378
```

