---
title: "Income Data from IRS"
author: "Fatemeh Kazemi"
date: "01-02-2021"
output:
  html_document:
    df_print: paged
---

### This program:
  (1) Reads and cleans income data by IRS and fill the gaps
     i. https://www.irs.gov/statistics/soi-tax-stats-individual-income-tax-statistics-zip-code-data-soi
  (2) Calculates site-level SES using the zipcodes in x-mile bufferzone of site

```{r load packages}
library(tidyverse)
library(here)
```

```{r}
#year
#zipcode  
#zip_level: zip SES  (normalized by State)
#state_level: state SES 
#zip_unnormalized: zip SES non-normalized)
#state

dt.ses.raw <- read.csv(here('data','raw','gross_income_by_state.csv'), sep = '') %>% 
  transmute(Zip.Code = str_pad(zipcode, 5, pad = "0"),
            State = state,
            Year = year,
            SES.Zip.Unorm = zip_unnormalized,
            SES.Zip.Norm = zip_level,
            SES.State = state_level) %>% 
  arrange(Zip.Code, Year)

zip.list <- dt.ses.raw %>% 
  distinct(Zip.Code, State)

dt.ses.zip = data.frame()
for (i in 2000:2008){
  dt0 <- tibble(zip.list, Year =i)
  dt.ses.zip <- rbind(dt.ses.zip, dt0)
}

dt.ses.zip <- full_join(dt.ses.zip, dt.ses.raw) %>% 
  arrange(Zip.Code, Year) %>% 
  group_by(Zip.Code) %>% 
  fill(SES.Zip.Unorm:SES.State, .direction = "downup")

save(dt.ses.zip, file = here('data', 'processed', 'ses-zip.RDa'))
write.csv(dt.ses.zip, file = here('data', 'processed', 'ses_zip.csv'))
```

```{r}
load(here('data', 'processed', 'ses-zip.RDa'))
load(here('data', 'processed', 'site-zip.RDa'))

# Count number of zipcode in each dataset
z.ses <- dt.ses.zip %>% distinct(Zip.Code) #40341
z.site <- dt.site.zip %>% distinct(Zip.Code) #40711
z.diff <- setdiff(z.ses$Zip.Code, z.site$Zip.Code) #2652

# 6-mile bufferzone around monitoring site
dt.ses.site.bz6 <- dt.site.zip %>% 
  inner_join(dt.ses.zip, by = c("Zip.Code", "Year")) %>% 
  filter(Dist <= 6) %>% 
  group_by(Site.ID, Year) %>% 
  summarise(SES.Zip.Unorm = mean(SES.Zip.Unorm),
            SES.Zip.Norm = mean(SES.Zip.Norm),
            SES.State = mean(SES.State))

save(dt.ses.site.bz6, file = here('data', 'processed', 'ses-site-bz6.RDa'))
write.csv(dt.ses.site.bz6, file = here('data', 'processed', 'ses-site-bz6.csv'))

dt.ses.site.bz6 %>% distinct(Site.ID) %>% nrow() #18157

# 12-mile bufferzone around monitoring site
dt.ses.site.bz12 <- dt.site.zip %>% 
  inner_join(dt.ses.zip, by = c("Zip.Code", "Year")) %>% 
  filter(Dist <= 12) %>% 
  group_by(Site.ID, Year) %>% 
  summarise(SES.Zip.Unorm = mean(SES.Zip.Unorm),
            SES.Zip.Norm = mean(SES.Zip.Norm),
            SES.State = mean(SES.State))

save(dt.ses.site.bz12, file = here('data', 'processed', 'ses-site-bz12.RDa'))
write.csv(dt.ses.site.bz12, file = here('data', 'processed', 'ses-site-bz12.csv'))

dt.ses.site.bz12 %>% distinct(Site.ID) %>% nrow() #18664

# 24-mile bufferzone around monitoring site
dt.ses.site.bz24 <- dt.site.zip %>% 
  inner_join(dt.ses.zip, by = c("Zip.Code", "Year")) %>% 
  filter(Dist <= 24) %>% 
  group_by(Site.ID, Year) %>% 
  summarise(SES.Zip.Unorm = mean(SES.Zip.Unorm),
            SES.Zip.Norm = mean(SES.Zip.Norm),
            SES.State = mean(SES.State))

save(dt.ses.site.bz24, file = here('data', 'processed', 'ses-site-bz24.RDa'))
write.csv(dt.ses.site.bz24, file = here('data', 'processed', 'ses-site-bz24.csv'))

dt.ses.site.bz12 %>% distinct(Site.ID) %>% nrow() #18664
```

